### PR TITLE
fix: #287 translation strigs are not exported

### PR DESCRIPTION
**Pull request by ghassanmas**
This is a fix of #287 . 

It just replace the function used to define messages as explined in the issue, and modifies `*.test` files when/if needed

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ghassanmas! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by brian-smith-tcril — APPROVED** [review]

**Comment by itsjeyd** [comment]
Hey @ghassanmas, thank you for this contribution! It looks like you already got approval for the changes. Could you bring the PR up to date with the base branch, and then ping @brian-smith-tcril for final approval?

**Comment by ghassanmas** [comment]
@itsjeyd @brian-smith-tcril done

**Review by brian-smith-tcril — APPROVED** [review]

**Review by deborahgu — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@ghassanmas 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learner-dashboard&entry.867055334=https://github.com/openedx/frontend-app-learner-dashboard/pull/293&entry.1484655318=https://github.com/ghassanmas&entry.752974735=2024-02-16+15:39&entry.1917517419=2024-02-22+22:25&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
