### PR TITLE
fix: get brand logo file path from env

### PR DESCRIPTION
**Pull request by shahbaz-shabbir05**
### Description:
While working on a project that involved customizing and testing a specific part of the system, I noticed a problem. The logo for this dashboard was fixed or hard-coded, which means it couldn't be easily changed or customized. To solve this issue, I made some changes in this PR.

Here's what I did in the PR:

- I made a modification to the code so that the logo's URL is not fixed within the code but is instead fetched from an env file. This way, we can change the logo by simply updating the configuration file without having to edit the code itself.

Related Issues: https://github.com/openedx/frontend-app-learner-dashboard/issues/176 & https://github.com/mitodl/hq/issues/1806

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @shahbaz-shabbir05!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by editing the PR title.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

**Comment by itsjeyd** [comment]
Hi @shahbaz-shabbir05, thank you for this contribution. Just to confirm, are the changes ready for review?

**Comment by shahbaz-shabbir05** [comment]
> Hi @shahbaz-shabbir05, thank you for this contribution. Just to confirm, are the changes ready for review?

Yes, the changes are ready for review.

**Review by cintnguyen — APPROVED** [review]
Tested locally, was able to rebase off of master with no conflicts. Tested with default settings and saw the default logo as expected. Tested manually by setting the environment variable (by running `LOGO_URL=fake.jpg npm start`) and saw broken brand logo image icon as expected.

**Comment by itsjeyd** [comment]
Hi @cintnguyen, thanks for the review! Do you know if we can consider your approval binding? I'm asking because as far as I can tell you're not part of the 2U team that owns this repo (Aurora), and I'm trying to understand if this PR will need a second review from that team before we can consider it ready for merge.

**Review by brian-smith-tcril — APPROVED** [review]
:shipit:

**Review by mattcarter — APPROVED** [review]
approved

**Pull request merged**
