### PR TITLE
fix: URLs get the current value of LMS_BASE_URL from getConfig()

### PR DESCRIPTION
**Pull request by mariajgrimaldi**
### Description
This PR is a backport for https://github.com/openedx/frontend-app-learner-dashboard/pull/273 so unenrollments work in the learner dashboard.

Resolves https://github.com/openedx/wg-build-test-release/issues/336

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mariajgrimaldi! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by itsjeyd** [comment]
Hey @jsnwesson, this is the backport for #273 which you merged yesterday. Mind giving it a quick look, too? :)

CC @arbrandes

**Comment by cmltaWt0** [comment]
Tested via a Tutor local deployment. Unenroll feature works great!
Also a Programs URL is formed correctly.

**Comment by cmltaWt0** [comment]
@itsjeyd I'm going to merge it since the upstream PR literally identical and we have to make a release today.

CC @arbrandes

**Comment by openedx-webhooks** [comment]
@mariajgrimaldi 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learner-dashboard&entry.867055334=https://github.com/openedx/frontend-app-learner-dashboard/pull/284&entry.1484655318=https://github.com/mariajgrimaldi&entry.752974735=2024-02-07+12:21&entry.1917517419=2024-02-09+09:26&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
