### PR TITLE
feat: display profile name in navbar if available

### PR DESCRIPTION
**Pull request by navinkarkera**
Display profile name if set, else fallback to username

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @navinkarkera! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Review by CefBoud — APPROVED** [review]

**Comment by jsnwesson** [comment]
Hey all! I'm responding for the Aperture team. Any chance this would need a product review, or could you add context for where this change is being requested? Thanks!

**Comment by hurtstotouchfire** [comment]
Once https://github.com/openedx/frontend-component-header/pull/466/files merges, we will replace this custom header in learner dash with the standard component header, and then I think https://github.com/openedx/frontend-component-header/pull/483 would provide this functionality, so likely this OSPR can just be closed.

That said, we should incorporate this into the product convo around removing username from the header. I think we'd need to pick between this approach and https://github.com/openedx/frontend-component-header/pull/465 which puts username behind a flag.

FYI @arbrandes / @jmakowski1123

**Comment by arbrandes** [comment]
@itsjeyd, I _think_ the proposal is this one:

https://openedx.atlassian.net/wiki/spaces/OEPM/pages/4060938253/Proposal+Autogenerate+username+behind+a+flag

@hurtstotouchfire, shall we close this PR, then?

**Comment by jsnwesson** [comment]
I'll go ahead and close this PR as there's already a PR #327  to replace the header with the `frontend-component-header`, which will allow us to customize the navbar in [that library with this PR](https://github.com/openedx/frontend-component-header/pull/466/files).

**Comment by openedx-webhooks** [comment]
@navinkarkera Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learner-dashboard&entry.867055334=https://github.com/openedx/frontend-app-learner-dashboard/pull/313&entry.1484655318=https://github.com/navinkarkera&entry.752974735=2024-04-09+10:37&entry.1917517419=2024-05-10+22:28&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
