### PR TITLE
fix: replace hardcoded strings and properly define i18n messages

### PR DESCRIPTION
**Pull request by brian-smith-tcril**
resolves https://github.com/openedx/frontend-app-learner-dashboard/issues/217

### CODE REVIEW

**Comment by brian-smith-tcril** [comment]
@hurtstotouchfire was the "waiting on author" label added because this needed a rebase?

**Comment by cintnguyen** [comment]
@brian-smith-tcril Tested this locally, I believe it needs to be rebased off of master once the painted door [PR](https://github.com/openedx/frontend-app-learner-dashboard/pull/218) is merged first. Otherwise it needs to include the `EXPERIMENT_08_23_VAN_PAINTED_DOOR=true` in order for the page to render.

After doing this on my end, ran `make extract_translations` and all three missing strings showed up in the transifix_input.json file generated. So this LGTM once it includes the env dev variable!

Side Question - Noticed that our layout is flipped when switching to the locale `ar`. Is this suppose to be the case?

**Review by cintnguyen — APPROVED** [review]
Tested this locally, ran make extract_translations and all three missing strings showed up in the transifix_input.json file generated. So this LGTM!

**Review by justinhynes — APPROVED** [review]

**Comment by justinhynes** [comment]
@brian-smith-tcril Hey there! This looks good to me but I can't seem to merge the changes with my current permissions. 

It looks like we may need to rebase these changes on the base/main branch before I can merge it.

If you could do that, I'll plan on merging it shortly afterwards.

(If I have write access, should I be able to automatically rebase the branch through GitHub? Maybe this feature isn't enabled on this repo?)

**Comment by arbrandes** [comment]
@brian-smith-tcril, mind rebasing?

**Pull request merged**
