### PR TITLE
Fixed issue  #510

### PR DESCRIPTION
**Pull request by Ankush1oo8**
Fixed the issue and added the main element ID "main"

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Ankush1oo8!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads


#### :radio_button: Submit a signed contributor agreement (CLA)

:warning: We ask all contributors to the Open edX project to submit a [signed contributor agreement](https://openedx.org/cla) or indicate their institutional affiliation.
Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md) file for more information.

If you've signed an agreement in the past, you may need to re-sign.
See [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/) for details.

Once you've signed the CLA, please allow 1 business day for it to be processed.
After this time, you can re-run the CLA check by adding a comment below that you have signed it.
If the CLA check continues to fail, you can tag the `@openedx/cla-problems` team in a comment for further assistance.






#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.



#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@2U-aperture`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

**Comment by deborahgu** [comment]
Thanks for the quick fix, @Ankush1oo8!

The actual fix here looks good, but there's some cleanup to make it approvable. This is covered in our [Quick Start: First Open edX Pull Request](https://docs.openedx.org/en/latest/developers/quickstarts/first_openedx_pr.html) doc if you want more details. 

### Non-blocking changes

These are things to just know for your next openEdx commit (and I hope there are more 😄 ).

*  You included many format changes (probably automatically produced by your IDE settings when you saved the file). As a general rule it's good to avoid this. 
     * Sometimes I want to lint an  existing file, so what I will do is make 2 separate pull requests, so the reviewer knows that one is style only.
* [We use Conventional Commits](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html#specification) for commit messages.

### Blocking changes

* Your  format changes don't match [our existing shared code-style](https://docs.openedx.org/en/latest/developers/references/developer_guide/style_guides/javascript-guidelines.html).
    * Now that the github actions have run you should be able to see those error messages. 
    * The easiest way to fix those errors is to just revert all the style changes. 
    * Most IDEs have a "save without formatting" option. In VS Code it's in the command palette.
* We'll need you to [sign the Contributor License Agreement](https://tcril.tfaforms.net/f/individual-cla)

**Comment by Ankush1oo8** [comment]
So should I change it and again send the PR

**Comment by Ankush1oo8** [comment]
Or will you change the format

**Comment by deborahgu** [comment]
> So should I change it and again send the PR

If you change the PR to remove the formatting changes, then I will test the fix locally. 

Assuming it works (which is looks like it will, but I have to verify) then as soon as we have your signed contributor agreement, I can approve.

**Comment by Ankush1oo8** [comment]
Okey I have filled the form for contributing

**Comment by Ankush1oo8** [comment]
I have made changes you told in a new pr please check it

**Pull request closed without merging**
