### PR TITLE
fix: display SUPPORT_URL only if is configured

### PR DESCRIPTION
**Pull request by dcoa**
**Description**

This PR removes the link of `SUPPORT_URL` from the Header if the service is not configured. 

It aims to solve the following issue https://github.com/openedx/frontend-app-learner-dashboard/issues/373 

**How to test**

1. Create a instance with `frontend-app-learner-dashobord` mounted in the current branch.
2. Launch the instance and open it in the browser.
3. Access the learner dashboard.
4. By default you should not see help nav button. 
6. Set the `SUPPORT_URL` config variable.
7. Now the tab should be available.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @dcoa!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads





#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.



#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@2U-aperture`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

**Comment by MaferMazu** [comment]
@dcoa, thanks for this PR.

I think it is easier to review if we split this PR by the issue the changes resolve <- But it is not a blocker comment.

About the Help button:
I think we should set the `SUPPORT_URL=''` in the `.env.development environment` like in production because we still have the issue in dev mode (the help button is enabled but not configured correctly), or using a working URL, for example http://local.edly.io:8000/help.
And change in `example.env.config.js` file to use a more accurate route.

Probably the best route for this is /help (maybe the localhost route + /help), which sends to a Help static template. Example: http://local.edly.io:8000/help
Because, in my understanding, the /support page is for staff members. Ref, the first Pr about the support page: https://github.com/openedx/edx-platform/pull/9240 (and you can access a /support as staff but not as a student or other roles)

And I am unsure about removing the variable `SUPPORT_URL` in the `.env.test`. I think it is better to have two tests, one when the variable is seated and another when the variable is missing.

About the programs:
I'll test it this week.

**Comment by MaferMazu** [comment]
**About programs:**
The functionality works as expected. I can't see the Programs tab when I don't have programs configured, but when I add the programs page as the discovery doc said here: https://github.com/overhangio/tutor-discovery?tab=readme-ov-file#show-programs-tab, the programs tab appears.

The only thing I have is that my Explore Programs button is redirecting to http://localhost:8080/programs, but I think it is for configuration issues rather than this PR.

**Comment by MaferMazu** [comment]
@arbrandes, can you help me find someone from the Frontend WG to review this? I left my comments, but I think I need more frontend experience to review the implementation.

**Comment by MaxFrank13** [comment]
Thanks for the contribution and addressing these two issues!

I agree with @MaferMazu that it would be ideal if we could break up this work into a PR for each issue. This helps if we need to roll back changes, especially since there is a different fix/implementation for each button. @dcoa what are your thoughts on this?

Aperture is the maintainer of this MFE and it would be ideal if we had a little time to get this on the docket for upcoming work. I have made an internal ticket for the team and we can prioritize it at the beginning of next week.

**Comment by dcoa** [comment]
@MaferMazu @MaxFrank13 thanks for your comments.

The reason that I created a single PR is because from a component perspective is the same issue, rendering of optional links, but I will be happy to split it in 2 and address the other comments.

**Review by MaxFrank13 — APPROVED** [review]
Thanks for splitting this up! This looks good to me and I've tested it in my local environment

**Review by arbrandes — APPROVED** [review]
LGTM!

**Review by MaferMazu — APPROVED** [review]
@dcoa, thanks for addressing my comments. I left other comments, but they were based on a previous version of this. This looks good to me. Thanks ✨

---
@arbrandes, we don't have permission to merge, so we need your help or @MaxFrank13's help to merge.

I know we are focused on the sumac cut, and I don't know if there is something we want to wait for or rush to merge this, but this is only to let you know that we don't have the powers.

**Pull request merged**
