### PR TITLE
feat: allow LOGO_URL runtime configuration

### PR DESCRIPTION
**Pull request by mariajgrimaldi**
### Description
This PR supports LOGO_URL runtime configurations, which can be taken from the `env` or the `MFE_CONFIG_OVERRIDES` configuration.

 ### How to test
I used a tutor development env for testing: 

1. Create an inline tutor plugin so you can add:
```
from tutor import hooks
hooks.Filters.ENV_PATCHES.add_item(
    (
        "openedx-lms-development-settings",

        """
LEARNER_HOME_MICROFRONTEND_URL = "http://{{MFE_HOST}}:1990"
LEARNER_HOME_MFE_REDIRECT_PERCENTAGE = 100
CORS_ORIGIN_WHITELIST.append("http://{{ MFE_HOST }}:1990")
LOGIN_REDIRECT_WHITELIST.append("{{ MFE_HOST }}:1990")
CSRF_TRUSTED_ORIGINS.append("http://{{ MFE_HOST }}:1990")
MFE_CONFIG_OVERRIDES = {
    "learner-dashboard": {
        "LOGO_URL": "https://files.edx.org/openedx-logos/edx-openedx-logo-tag.png"
    }
}
"""
    )
)
```
2. After cloning this repo, modify .env.development so it looks like this:
```
NODE_ENV='development'
PORT=1990
BASE_URL='apps.local.overhang.io:1990'
LMS_BASE_URL='http://local.overhang.io:8000'
ECOMMERCE_BASE_URL='http://localhost:18130'
LOGIN_URL='http://local.overhang.io:8000/login'
LOGOUT_URL='http://local.overhang.io:8000/logout'
LOGO_URL=https://edx-cdn.org/v3/default/logo.svg
LOGO_TRADEMARK_URL=https://edx-cdn.org/v3/default/logo-trademark.svg
LOGO_WHITE_URL=https://edx-cdn.org/v3/default/logo-white.svg
LOGO_POWERED_BY_OPEN_EDX_URL_SVG=https://edx-cdn.org/v3/stage/open-edx-tag.svg
FAVICON_URL=https://edx-cdn.org/v3/default/favicon.ico
CSRF_TOKEN_API_PATH='/csrf/api/v1/token'
REFRESH_ACCESS_TOKEN_ENDPOINT='http://local.overhang.io:8000/login_refresh'
ACCESS_TOKEN_COOKIE_NAME='edx-jwt-cookie-header-payload'
USER_INFO_COOKIE_NAME='edx-user-info'
SITE_NAME=localhost
DATA_API_BASE_URL='http://localhost:8000'
// LMS_CLIENT_ID should match the lms DOT client application id your LMS containe
LMS_CLIENT_ID='login-service-client-id'
SEGMENT_KEY=''
FEATURE_FLAGS={}
MARKETING_SITE_BASE_URL='http://local.overhang.io:8000'
SUPPORT_URL='http://local.overhang.io:8000/support'
CONTACT_URL='http://local.overhang.io:8000/contact'
OPEN_SOURCE_URL='http://local.overhang.io:8000/openedx'
TERMS_OF_SERVICE_URL='http://local.overhang.io:8000/terms-of-service'
PRIVACY_POLICY_URL='http://local.overhang.io:8000/privacy-policy'
FACEBOOK_URL='https://www.facebook.com'
TWITTER_URL='https://twitter.com'
YOU_TUBE_URL='https://www.youtube.com'
LINKED_IN_URL='https://www.linkedin.com'
REDDIT_URL='https://www.reddit.com'
APPLE_APP_STORE_URL='https://www.apple.com/ios/app-store/'
GOOGLE_PLAY_URL='https://play.google.com/store'
ENTERPRISE_MARKETING_URL='http://example.com'
ENTERPRISE_MARKETING_UTM_SOURCE='example.com'
ENTERPRISE_MARKETING_UTM_CAMPAIGN='example.com Referral'
ENTERPRISE_MARKETING_FOOTER_UTM_MEDIUM='Footer'
LEARNING_BASE_URL='http://localhost:2000'
SESSION_COOKIE_DOMAIN='local.overhang.io'
ZENDESK_KEY=''
HOTJAR_APP_ID=''
HOTJAR_VERSION='6'
HOTJAR_DEBUG=''
ACCOUNT_SETTINGS_URL='http://localhost:1997'
ACCOUNT_PROFILE_URL='http://localhost:1995'
ENABLE_NOTICES=''
CAREER_LINK_URL=''
OPTIMIZELY_FULL_STACK_SDK_KEY=''
APP_ID='learner-dashboard'
MFE_CONFIG_API_URL='/api/mfe_config/v1'
EXPERIMENT_08_23_VAN_PAINTED_DOOR=false
ENABLE_EDX_PERSONAL_DASHBOARD=true
```
4. Then run:
```
nvm use 18.0.0
npm install
npm start
```

Then:
image

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mariajgrimaldi! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by itsjeyd** [comment]
@mariajgrimaldi Thank you for this contribution! Let us know when the changes are ready for review.

**Comment by mariajgrimaldi** [comment]
@itsjeyd: it's ready! Thanks

**Review by arbrandes — APPROVED** [review]
👍🏼

**Comment by itsjeyd** [comment]
@mariajgrimaldi Looks like this just needs a rebase and then it will be ready for merge.

**Comment by itsjeyd** [comment]
Hey @mariajgrimaldi, a friendly ping about [rebasing this](https://github.com/openedx/frontend-app-learner-dashboard/pull/238#issuecomment-1815943059) to get it ready for merge.

CC @hurtstotouchfire

**Comment by mariajgrimaldi** [comment]
@itsjeyd: Done! Thanks

**Comment by arbrandes** [comment]
Looks like a version of this already got in master!  Thanks, @mariajgrimaldi!

**Comment by openedx-webhooks** [comment]
@mariajgrimaldi Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learner-dashboard&entry.867055334=https://github.com/openedx/frontend-app-learner-dashboard/pull/238&entry.1484655318=https://github.com/mariajgrimaldi&entry.752974735=2023-11-07+16:52&entry.1917517419=2023-12-06+12:17&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
