### PR TITLE
feat: add translations for Persian language

### LINKED ISSUE #270: No translations for Persian language
Hi all. Translations for Persian language (`fa` and / or `fa-ir`) is not currently available neither in Quince nor in master. As leaner dashboard is set as default dashboard by tutor, it would be great to have translations for Persian as well.

### PR DESCRIPTION
**Pull request by FatemeKhodayari**
Translations for Persian (fa-ir language code) are added so the learner dashboard MFE will be usable for Persian users.

Closes #270

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @FatemeKhodayari! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by itsjeyd** [comment]
Hi @FatemeKhodayari! Thank you for your contribution! I'm lining the changes up for a test run.

**Comment by itsjeyd** [comment]
@FatemeKhodayari Looks like we've got a green build! I'm marking this PR as ready for review, but let me know if you were planning on making further changes to it.

**Comment by FatemeKhodayari** [comment]
> @FatemeKhodayari Looks like we've got a green build! I'm marking this PR as ready for review, but let me know if you were planning on making further changes to it.

Thanks for the checks and feedback. I just can check transifex for possible updates if you think it's needed. But aside from that, I don't think I have anything to add for now. Shall I sync everything with transifex or is it fine the way it is?

**Comment by itsjeyd** [comment]
Thanks for the details @FatemeKhodayari. I don't have enough context to answer your question, which means that it would definitely be a good time to get engineering review started :)

@leangseu-edx Would you be able to take a look at this PR?

**Comment by itsjeyd** [comment]
Hi @viktorrusakov, I see that you're [listed as a core contributor](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3156344833/Core+Contributors+to+the+Open+edX+Project) for all `frontend-*` repos. Would you be able to help out here and review this PR?

For context, one of the decisions made at the first meeting of the new Maintenance WG last week was that we can let CCs [take on Reviews and Merges that they can manage](https://openedx.atlassian.net/wiki/spaces/COMM/pages/4031578215/2024-02-01+Meeting+notes#%E2%A4%B4-Decisions). That will hopefully help us get reviews for community contributions more quickly, and is why I'm pinging you here :)

CC @FatemeKhodayari

**Comment by viktorrusakov** [comment]
HI @itsjeyd! You can absolutely tag me on PRs that need help with reviews, but I'm not sure I'll be able to help much with this one as I don't know what is the current process for adding a new language to MFEs.

The code changes look good to me and I see that these translations are present in the [Transifex](https://app.transifex.com/open-edx/edx-platform/viewstrings/#fa_IR/frontend-app-learner-dashboard/477084659) resourse for this MFE, which means they will get updated automatically. I _think_ this should be enough for this PR to get merged but I also know that there is an ongoing (maybe even finished already?) work on changing translations pipelines in repositories, so maybe there are additional steps we need to do which I'm not aware of.

@brian-smith-tcril could you help with this PR? I think you were heavily involved in changing translations' workflows project. Just want to make sure this is OK to merge.

**Comment by FatemeKhodayari** [comment]
Hi guys. I just merged master into my branch to keep it updated but then I realised that the approved workflows have gone back to "awaiting approval" state. Hope I haven't disrupted the process. Generally, what is the openedx policy for this situation? Should the developer keep the branch updated with master at all stages before merge? 

@itsjeyd @viktorrusakov @mphilbrick211

**Comment by jsnwesson** [comment]
Hey all! I'm responding on behalf of the Aperture team just to say that I've got eyes on this as well, but since our team is no longer responsible for translations I can't confidently speak on what the new translation system requires for new languages. What I can do is at least make this PR known in the openedx #wg-translations channel, and hopefully we can get this merged sooner than later!

**Comment by OmarIthawi** [comment]
@FatemeKhodayari Thanks for your contribution.

Unfortunately, at the moment we don't support this workflow anymore and we're removing all the languages from Micro-frontends. Please see the related removal pull request:

- https://github.com/openedx/frontend-app-learner-dashboard/pull/227

Since you've already merged that in your master I suggest keeping those change in your fork until Redwood in which a new approach will be used:

- https://github.com/overhangio/tutor-mfe/pull/184

You're welcome to start testing the experimantal `atlas pull` in Tutor MFE before it's merged and it will provide you with the latest translations on every build without needing to open pull requests like this.

Please take a look at the [OEP-58 proposal](https://docs.openedx.org/en/latest/developers/concepts/oep58.html) which has been implemented and scheduled to be released in Redwood.

I recommend closing this pull request.

**Comment by FatemeKhodayari** [comment]
> @FatemeKhodayari Thanks for your contribution.
> 
> Unfortunately, at the moment we don't support this workflow anymore and we're removing all the languages from Micro-frontends. Please see the related removal pull request:
> 
> * [feat!: remove Transifex calls for OEP-58 | FC-0012 #227](https://github.com/openedx/frontend-app-learner-dashboard/pull/227)

Hi Omar. Thanks for the feedback. Merging and getting all translations from a single source sounds like a good idea to me. Thanks for letting me know. 

> Since you've already merged that in your master I suggest keeping those change in your fork until Redwood in which a new approach will be used:
> 
> * [feat: enable `atlas pull` for all MFEs | FC-0012 overhangio/tutor-mfe#184](https://github.com/overhangio/tutor-mfe/pull/184)
> 
> You're welcome to start testing the experimantal `atlas pull` in Tutor MFE before it's merged and it will provide you with the latest translations on every build without needing to open pull requests like this.

Actually I haven't merged these changes into the master branch of my fork, I have them in a separate branch. I merged the remote master into this branch to keep it updated but that doesn't matter now :)) 

About `atlas pull`, you mean the command in the `# Experimental: OEP-58 Pulls translations using atlas` section of Makefile? Suppose this change won't affect customized translations applied by Tutor, right?

**Comment by OmarIthawi** [comment]
> About `atlas pull`, you mean the command in the `# Experimental: OEP-58 Pulls translations using atlas` section of Makefile? Suppose this change won't affect customized translations applied by Tutor, right?

Yes @FatemeKhodayari. Running `make OPENEDX_ATLAS_PULL=yes pull_translations` should provide your Micro-frontend with the latest translations.

This is a Redwood feature which is being merged as we speak:

 - https://github.com/overhangio/tutor-mfe/pull/184

**Comment by FatemeKhodayari** [comment]
> Yes @FatemeKhodayari. Running `make OPENEDX_ATLAS_PULL=yes pull_translations` should provide your Micro-frontend with the latest translations.

So, I guess from now on, only translations from `openedx-translations` project of transifex will appear when you pull? What about languages that aren't present in this project? For example, Persian existed in the edx-platform project of transifex but not in the openedx-translations project. 

Someone requested Persian (fa-ir) some time ago in the openedx-translations project in transifex but it still isn't available for translation.

**Comment by OmarIthawi** [comment]
> So, I guess from now on, only translations from `openedx-translations` project of transifex will appear when you pull? What about languages that aren't present in this project? For example, Persian existed in the `edx-platform` project of transifex but not in the `openedx-translations` project.

Yes.

> Someone requested Persian (fa-ir) some time ago in the `openedx-translations` project in transifex but it still isn't available for translation.

Please ping @ehuthmacher about the list of the languages we'll be adding. I believe the plan is to add about 100 more language including Persian.

cc: @shadinaif

**Comment by itsjeyd** [comment]
@FatemeKhodayari Just checking in about next steps. Are you planning on closing this PR as @OmarIthawi suggested [above](https://github.com/openedx/frontend-app-learner-dashboard/pull/271#issuecomment-1937015349)?

**Comment by FatemeKhodayari** [comment]
> @FatemeKhodayari Just checking in about next steps. Are you planning on closing this PR as @OmarIthawi suggested [above](https://github.com/openedx/frontend-app-learner-dashboard/pull/271#issuecomment-1937015349)?

Yes sure. Hope Persian is added to the `openedx-translations` of transifex soon :)

**Comment by openedx-webhooks** [comment]
@FatemeKhodayari Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learner-dashboard&entry.867055334=https://github.com/openedx/frontend-app-learner-dashboard/pull/271&entry.1484655318=https://github.com/FatemeKhodayari&entry.752974735=2024-01-13+09:05&entry.1917517419=2024-02-17+04:36&entry.2133058324=No) so we can improve your experience in the future.

**Comment by ehuthmacher** [comment]
@FatemeKhodayari, yes, we will add Persian to the openedx-translations in TX this week.

**Comment by FatemeKhodayari** [comment]
> @FatemeKhodayari, yes, we will add Persian to the openedx-translations in TX this week.

Hello @ehuthmacher! That's great new! Thanks a lot :)

**Pull request closed without merging**
