### PR TITLE
fix: test mock cleanup for useMemo

### PR DESCRIPTION
**Pull request by nsprenkle**
Split out test cleanup from https://github.com/edx/frontend-app-learner-dashboard/pull/68 for better modularity.

### CODE REVIEW

**Review by muselesscreator — APPROVED** [review]
LGTM

**Comment by nsprenkle** [comment]
Holding until NOV 21 post release cycle

**Comment by justinhynes** [comment]
Hi @nsprenkle!

I see that this was approved but never merged. I'm trying to clean up some older PRs in this repo. Is this PR still needed? If so, would you be able to fix up the conflicts so we can see to getting this merged?

Thanks in advance!

**Comment by justinhynes** [comment]
I haven't heard back and this PR is over a year old. Please resubmit a new PR if you'd like to get this change merged!

**Pull request closed without merging**
