### PR TITLE
feat: updated frontend-build & frontend-platform major versions

### PR DESCRIPTION
**Pull request by BilalQamar95**
**Description**
Major version upgrades, Updating `frontend-build` to v14 & `frontend-platform` to v8 along with respective edx packages

### CODE REVIEW

**Comment by deborahgu** [comment]
is this work still in progress or can we go ahead and close this PR?  if it's still in progress, anything we can do to help out with it?

**Comment by BilalQamar95** [comment]
@deborahgu this PR is now ready for review

**Comment by jsnwesson** [comment]
I think this looks good to me, but my one concern is that 18 tests are failing _locally_ due to three different errors: 
- TypeError: Cannot read properties of undefined (reading 'default')
  - import '@testing-library/jest-dom/extend-expect'; 
  - example above found in test files like `App.test.jsx`
- TypeError: Cannot read properties of undefined (reading 'getConfig')
  - export const routePath = `${getConfig().PUBLIC_PATH}:courseId`; 
- TypeError: Cannot read properties of undefined (reading 'notEnrolled')
  - [FilterKeys.notEnrolled]: (course) => !course.enrollment.isEnrolled,
  - example above found in test file `FilterForm.test.jsx`

**Comment by BilalQamar95** [comment]
> I think this looks good to me, but my one concern is that 18 tests are failing _locally_ due to three different errors:
> 
> * TypeError: Cannot read properties of undefined (reading 'default')
>   
>   * import '@testing-library/jest-dom/extend-expect';
>   * example above found in test files like `App.test.jsx`
> * TypeError: Cannot read properties of undefined (reading 'getConfig')
>   
>   * export const routePath = `${getConfig().PUBLIC_PATH}:courseId`;
> * TypeError: Cannot read properties of undefined (reading 'notEnrolled')
>   
>   * [FilterKeys.notEnrolled]: (course) => !course.enrollment.isEnrolled,
>   * example above found in test file `FilterForm.test.jsx`

@jsnwesson I have tried running the tests locally again, and all tests are passing successfully for me. My team members have also confirmed that they are not encountering any test failures. It would be helpful if you could provide more details so we can better understand and reproduce the issue

`node: v18.20.2`
`npm: 10.5.0`
Screenshot 2024-05-21 at 4 35 05 PM

**Comment by justinhynes** [comment]
FWIW, I am also seeing tests failing locally:
image

I pulled the latest changes, switched to the `bilalqamar95/jest-v29-upgrade` branch, and issued an `npm ci` to install dependencies. I ran tests with the `npm test` command. 

Raw logs from local test run uploaded here: 
[local_logs.txt](https://github.com/openedx/frontend-app-learner-dashboard/files/15389615/local_logs.txt)

**Comment by justinhynes** [comment]
I'll try this now.

**Comment by justinhynes** [comment]
Unfortunately, I'm having the same issue. After deleting my `node_modules/` folder, reinstalling dependencies and running tests (`npm test`), I am still having the same 19 tests fail. 

🤔

**Comment by jsnwesson** [comment]
@justinhynes well, I managed to find the problem! Once I deleted my `env.config.js`, all of the tests passed! Now a new concern is: why did the tests fail with the `env.config.js` that I had, and can we be confident that this won't be the case for our stage/production builds? 
```
import { PLUGIN_OPERATIONS, DIRECT_PLUGIN } from "@openedx/frontend-plugin-framework";

import RecommendationsPanel from 'widgets/RecommendationsPanel';

const config = {
  pluginSlots: {
    course_list: {
      keepDefault: true,
      plugins: [
        // {
        //   op: PLUGIN_OPERATIONS.Insert,
        //   widget: {
        //     id: 'recommendations_plugin',
        //     type: DIRECT_PLUGIN,
        //     priority: 60,
        //     RenderWidget: RecommendationsPanel,
        //   },
        // },
      ],
    },
    widget_sidebar_plugin_slot: {
      keepDefault: true,
      plugins: [
        // {
        //   op: PLUGIN_OPERATIONS.Insert,
        //   widget: {
        //     id: 'recommendations_plugin',
        //     type: DIRECT_PLUGIN,
        //     priority: 60,
        //     RenderWidget: RecommendationsPanel,
        //   },
        // },
      ],
    },
  },
};

export default config;
```

**Review by jsnwesson — APPROVED** [review]
Just to make it clear, I think this code looks good and can move forward once the package-lock conflicts are resolved.

**Pull request merged**
