### PR TITLE
fix:  added main id to main block 

### PR DESCRIPTION
**Pull request by Ankush1oo8**
Fixed the issue #510  and did not make any changes in format as per the instructions

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Ankush1oo8!

### What's next?

*Please work through the following steps to get your changes ready for engineering review:*

#### :radio_button: Get product approval

If you haven't already, [check this list](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Does-my-contribution-require-Product-Review%3F) to see if your contribution needs to go through the product review process.

- If it does, you'll need to submit a product proposal for your contribution, and have it reviewed by the [Product Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3449028609/Product+Working+Group).
    - This process (including the steps you'll need to take) is documented [here](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review#Product-Review-Process).
- If it doesn't, simply proceed with the next step.

#### :radio_button: Provide context

To help your reviewers and other members of the community understand the purpose and larger context of your changes, feel free to add as much of the following information to the PR description as you can:

- Dependencies
  > This PR must be merged before / after / at the same time as ...
- Blockers
  > This PR is waiting for OEP-1234 to be accepted.
- Timeline information
  > This PR must be merged by XX date **because** ...
- Partner information
  > This is for a course on edx.org.
- Supporting documentation
- Relevant [Open edX discussion forum](https://discuss.openedx.org/) threads


#### :radio_button: Submit a signed contributor agreement (CLA)

:warning: We ask all contributors to the Open edX project to submit a [signed contributor agreement](https://openedx.org/cla) or indicate their institutional affiliation.
Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md) file for more information.

If you've signed an agreement in the past, you may need to re-sign.
See [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/) for details.

Once you've signed the CLA, please allow 1 business day for it to be processed.
After this time, you can re-run the CLA check by adding a comment below that you have signed it.
If the CLA check continues to fail, you can tag the `@openedx/cla-problems` team in a comment for further assistance.






#### :radio_button: Get a green build

If one or more checks are failing, continue working on your changes until this is no longer the case and your build turns green.



#### :radio_button: Let us know that your PR is ready for review:

### Who will review my changes?


This repository is currently maintained by `@2U-aperture`.  Tag them in a comment and let them know that your changes are ready for review.


### Where can I find more information?

If you'd like to get more details on all aspects of the review process for open source pull requests (OSPRs), check out the following resources:

- [Overview of Review Process for Community Contributions](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/FAQ-about-pull-requests.html)
- [Pull Request Status Guide](https://docs.openedx.org/en/latest/developers/references/developer_guide/process/pull-request-statuses.html)
- [Making changes to your pull request](https://docs.openedx.org/en/latest/documentors/how-tos/make_changes_to_your_pull_request.html)

### When can I expect my changes to be merged?

Our goal is to get community contributions seen and reviewed as efficiently as possible.

However, the amount of time that it takes to review and merge a PR can vary significantly based on factors such as:

- The size and impact of the changes that it introduces
- The need for product review
- Maintenance status of the parent repository

:bulb: *As a result it may take up to several weeks or months to complete a review and merge your PR.*

**Review by jsnwesson — COMMENTED** [review]
I went ahead and tested this, and it looks good so far. I provided a recording to show that keyboard and screenreader navigation are closer to working as they should, but this fix exposed another bug where for some reason the first announcement is about the passing grade for the bottom-most course. If you want to try to fix that in this PR, it'd be great, otherwise I think you can open another issue ticket to address it for future work.  

Aside from that, I'll wait to approve this until some of the other failing tasks are addressed: 
- you'll need to fix the lint errors that are noted by the linter
- ensure the CLA is signed and approved
- and I'm going to predict that a failing test will eventually be that the Jest Snapshot isn't going to pass with this new change. To update the Jest Snapshot, you can run `npm run snapshot` in your terminal and push the `App.test.jsx.snap` file to your PR. 

Let me know if you have any questions!

**Comment by jsnwesson** [comment]
Uploading Screen Recording 2024-11-27 at 10.33.49 AM.mov…

**Comment by Ankush1oo8** [comment]
What is the lint error in the code

**Comment by jsnwesson** [comment]
@Ankush1oo8 you can find the lint errors by running `npm run lint` and fix it with `npm run lint-fix`, but you can also see them being flagged in [GitHub by going to the file page](https://github.com/openedx/frontend-app-learner-dashboard/pull/512/files)

**Comment by jsnwesson** [comment]
And although it's not an actual blocker, if you can fix your commit message by following [the OEP-51 document](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html), that'll pass your first test.

**Comment by Ankush1oo8** [comment]
Okey 😁

**Comment by Ankush1oo8** [comment]
> And although it's not an actual blocker, if you can fix your commit message by following [the OEP-51 document](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html), that'll pass your first test.


sir can you what is wrong in the new commit

**Comment by jsnwesson** [comment]
@Ankush1oo8 Ah! All that was missing is the `:` in between the tag and the commit message. 

`fix lint and format` --> `fix: lint and format`

You had done it correctly before, but I think that you're still going to need to fill out the Contributor Agreement (CLA) if you haven't already. I'm not responsible for the CLA process, so I'm not sure if you already filled it out and are just waiting to be approved.

**Comment by Ankush1oo8** [comment]
I have filled it but did not receive any info about verification

**Comment by jsnwesson** [comment]
Ah! Then it could be that the person verifying it still needs to take a look at it 😄 

One thing you can do while you wait is also make sure to update this branch with any new changes that occur from other Pull Requests. You can do that by clicking on the `Update Branch` button below.

**Comment by Ankush1oo8** [comment]
I have updated the branch

**Comment by jsnwesson** [comment]
@Ankush1oo8 I'm also looking into why the Node CI test is failing for an email notification, which I don't think has to do with your work. I've seen this in other PRs for this repo. 

In the mean time, I think now you just need to wait on getting your CLA verified before this PR can be merged.

**Comment by itsjeyd** [comment]
@Ankush1oo8 It looks like commitlint is still reporting some issues. Could you please fix those? [This comment](https://github.com/openedx/frontend-app-learner-dashboard/pull/512#issuecomment-2512260418) should have the info that you'll need.

**Comment by Ankush1oo8** [comment]
> @Ankush1oo8 It looks like commitlint is still reporting some issues. Could you please fix those? [This comment](https://github.com/openedx/frontend-app-learner-dashboard/pull/512#issuecomment-2512260418) should have the info that you'll need.

Can you check now I have made the change

**Comment by jsnwesson** [comment]
@Ankush1oo8 the commitlint will check all of your commits, so although some use the correct syntax (ie. `fix: lint checks`) you'll need to fix all of them to [follow the commit syntax that I linked](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html).

**Comment by Ankush1oo8** [comment]
So can I edit the commit messages

**Pull request closed without merging**
